location ^~ /mylib {
    root /srv;
    index index.php;
    try_files $uri /mylib/index.php$is_args$args;

    location ~ \.php$ {
        add_header 'Content-Security-Policy' 'worker-src * blob:';

        fastcgi_split_path_info ^/mylib(.+?\.php)(/.*)?$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /application/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
        fastcgi_intercept_errors on;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_pass 172.101.0.101:9000;
        fastcgi_index index.php;
    }
}
